src/Entity/TextEntry.php
<?php

namespace App\Entity;

use App\Repository\TextEntryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TextEntryRepository::class)
 */
class TextEntry
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="textEntries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/UserProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserProfileController extends AbstractController
{
    /**
     * @Route("/user/{username}", name="user_profile")
     * @ParamConverter("user", class="App\Entity\User")
     */
    public function index(User $user): Response
    {
        return $this->render('user_profile/index.html.twig', [
            'controller_name' => 'UserProfileController',
            'user' => $user
        ]);
    }

    /**
     * @Route("/me", name="current_user_profile")
     */
    public function me(Request $request)
    {
        $user = $this->getUser();

        if(is_null($user)) {
            return $this->redirectToRoute('app_login');
        } else {
            return $this->render('user_profile/index.html.twig', [
                'controller_name' => 'UserProfileController',
                'user' => $user
            ]);
        }
    }
}

templates/user_profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.username }} blog{% endblock %}

{% block body %}
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <h2>{{ user.username }}</h2>
            </div>
        </div>
        {% if app.request.pathinfo == "/me" %}
            <div class="row">
                <div class="col">
                    <div class="d-grid gap-2">
                        <a href="{{ path('text_entry') }}" class="btn btn-primary">Add blog entry</a>
                    </div>
                </div>
            </div>
        {% endif %}
        {% if user.textEntries is empty %}
            <hr>
            <div class="row">
                <p>It's empty here for now, user didn't post anything on his cool text blog.</p>
            </div>
        {% endif %}
        {% for entry in user.textEntries %}
            <hr>
            <div class="row">
                <p>{{ entry.content }}</p>
                <time>{{ entry.creationDate|date("Y-m-d H:i:s") }}</time>
            </div>
        {% endfor %}
    </div>
</main>
{% endblock %}